#+title: Session du 2022-03-11

* 26 Aubentag

Départ puis arrivée à Altdorf en fin d'après-midi. Deux hommes
étranges font des signes à Wanda sans que celle-ci n'en comprenne la
signification, les deux hommes finissent pas se lancer à la suite d'un
homme trapue. Les aventuriers rencontre Josef Quartjin, un vieil ami
de Johann, qui leur propose de les embaucher pour l'aider à mener sa
barge à Bögenhaffen.

Dans une auberge, les joueurs se font provoquer par des jeunes nobles
stupides et fins saouls. Un début de bagarre se déclenche puis tout le
monde s'en va.

En allant au bateau les aventuriers remarquent que les deux hommes
étranges qui avaient fait des signes à Wanda les suivent. Les joueurs
cherchent à les piéger mais ils ne retrouvent que leurs cadavres,
tués à coup de carreaux d'arbalète.

En fouillant les cadavres, les aventuriers découvrent qu'ils portent
tous les deux une main mauve tatouée sur le sein droit.

* 27 Marktag
Le matin, les aventuriers apprennent qu'un des nobles qui les avaient
provoqué avait été assassiné et qu'ils sont recherchés pour le
meurtre ! Ils se dépêchent alors de partir pour Bögenhaffen en prenant
le canal de Weißbrück.

* 28 Backertag
Journée paisible sur le canal

* 29 Bezahltag
Arrivée à Weißbrück. Les aventuriers repèrent l'homme trapue aperçu à
Altdorf, armé d'une arbalète. Sur leur garde, ils se font attaqués le
soir par le même homme et trois brute qui incendie le bateau. Pendant
que Josef et son équipage éteint le feu, les aventuriers tuent les
brutes puis l'homme trapu, Adolphus Kuftsos.

Ce dernier détient une lettre où on lui donne des renseignements sur
une certaine Kastelle Lieberung dont le portrait ressemble trait pour
trait à Wanda.
* 30 Konistag
Réparation du bateau, courses à Weißbrück.
* 31 Angerstag
Journée paisible sur le canal.
* 32 Festag 
Journée paisible sur le canal.
* 33 Wellentag
Journée paisible sur le canal.
