#+title: Session du 2022-03-18

* Mitterfrühl
Arrivée à Bögenhaffen, début de la Schaffenfest.

Les aventuriers apprennent que l'héritage était en fait un canular.

Harbull bourré défie un lutteur professionnel et manque de mourir.

Malmir rattrape un gobelin à trois pattes pour le compte du Docteur
Malthusius, un montreur de foire.

Plus tard, le gobelin s’enfuit à nouveau et file dans les
canalisations de la ville. Le magistrat Richter, craignant que le
gobelin sème le panique en ville et Le docteur Malthusius, souhaitant
récupérer sa précieuse créature demandent aux aventuriers d’aller le
chercher dans les égouts de la ville.

Durant leur chemin dans les égouts, les aventuriers trouvent une
entrée d’une planque de la guilde des voleurs. Ils trouvent enfin un
temple, d’où une traînée de sang se déverse dans le canal. Ils
trouvent dans le temple les restes du gobelin, mangé par un démon qui
fait fuir les aventuriers.

Les aventuriers ont le temps de noter quelques détails :

- un pentacle dessiné à l’intérieur d’un cerceau de cuivre, au cœur du
  pentacle se trouve une tête de bête autour de laquelle on peut lire
  « Ordo Septenarius » ;
- prêt d’une armoire vous apercevez un mouchoir avec les initiales
  FS.
