* Sigmarzeit, 14 festag
  Alors qu’ils remontent le Reik, les aventuriers et aventurières sont
  hélés par deux nains qui demandent à être pris à bord contre une
  grosse somme d’argent. Alors qu’ils discutent le prix du trajet un
  vieux nains furieux reprend les deux autostoppeurs et les renvoie au
  travail.

  Aynjulls Isembard est très ennuyé. Plusieurs accidents
  incompréhensibles sont arrivés sur son chantier et un ouvrier a même
  disparu. Il a peur de perdre la face si le chantier n’est pas fini à
  temps et ses ouvriers ont peur de mal finir aussi. Les aventuriers
  et aventurières acceptent de l’aider.

  En surveillant le chantier la nuit, ils voient surgir une goule du
  socle sur lequel le sémaphore est construit. Une fois la goule tuée,
  ils se rendent compte que son pendentif actionne une porte magique
  dans le socle. En rentrant dans le socle, ils tombent dans un petit
  corridor avec trois portes. Ils ouvrent la porte sur leur gauche et
  découvrir un laboratoire d’alchimie gardé par un zombie.
  
